spring.application.name=Gp3
spring.docker.compose.enabled=false
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/voting_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.web.resources.static-locations=classpath:/static/,file:./candidates_images/

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true